#!/bin/bash
set -euo pipefail

# tile-smush doesn't do multithreading, but can be told to operate on only
# a slice of tiles.
#
# To achieve multithreading (without running into sqlite's intra-process mutexes),
# we launch multiple processes that each take a disjoint set of work.

rm -f merged.mbtiles*

pids=()

kill_children() {
	for pid in ${pids[*]}; do
		kill $pid
	done
}

trap kill_children INT

export SHARDS=16
for i in $(seq 0 $((SHARDS - 1))); do
	SHARD=$i ./tile-smush "$@" &
	pids[${i}]=$!
done

for pid in ${pids[*]}; do
	wait $pid
done
echo "PRAGMA journal_mode=OFF;" | sqlite3 merged.mbtiles
